=== TrackerSB/DriveBuild/schemes/drivebuild.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="environment">
        <xs:complexType>
            <xs:all>
                <xs:element name="author" type="xs:string"/>
                <xs:element name="name" type="xs:ID"/>
                <xs:element name="version" type="positiveDecimal"/>

                <xs:element name="lanes" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lane" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="laneSegment" minOccurs="2" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attributeGroup ref="positionAttributes"/>
                                                <xs:attribute name="width" type="positiveDecimal" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/> <!-- FIXME Exclude offroad as ID -->
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="obstacles" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="obstacle" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attributeGroup ref="positionAttributes"/>
                                    <xs:attribute name="width" type="positiveDecimal" use="required"/>
                                    <xs:attribute name="length" type="positiveDecimal" use="required"/>
                                    <xs:attribute name="height" type="positiveDecimal" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="criteria">
        <xs:complexType>
            <xs:all>
                <xs:element name="participants">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="participant" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="initialState">
                                            <xs:complexType>
                                                <xs:attributeGroup ref="movementGroup"/>
                                                <xs:attribute name="orientation" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:decimal">
                                                            <xs:minInclusive value="0"/>
                                                            <xs:maxExclusive value="360"/>
                                                            <xs:fractionDigits value="2"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="model" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="etk800"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="ai" minOccurs="0">
                                            <xs:complexType>
                                                <xs:attribute name="address" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="movement" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="waypoint" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attributeGroup ref="movementGroup"/>
                                                            <xs:attributeGroup ref="positionAttributes"/>
                                                            <xs:attribute name="tolerance" type="positiveDecimal"
                                                                          use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="precondition" type="criterion"/>
                <xs:element name="success" type="criterion"/>
                <xs:element name="failure" type="criterion"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <!-- Basic types -->
    <xs:attributeGroup name="positionAttributes">
        <xs:attribute name="x" type="xs:decimal" use="required"/>
        <xs:attribute name="y" type="xs:decimal" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="positiveDecimal">
        <xs:simpleContent>
            <xs:restriction base="xs:decimal">
                <xs:minExclusive value="0"/>
                <xs:fractionDigits value="2"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Types for participants -->
    <xs:complexType name="aiMode">
        <xs:simpleContent>
            <xs:restriction base="xs:string">
                <xs:enumeration value="manual"/>
                <xs:enumeration value="autonomous"/>
                <xs:enumeration value="training"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>

    <xs:attributeGroup name="movementGroup">
        <xs:attributeGroup ref="positionAttributes"/>
        <xs:attribute name="aiMode" type="aiMode" use="required"/>
        <xs:attribute name="speed" type="xs:nonNegativeInteger"/>
        <xs:attribute name="speedLimit" type="xs:nonNegativeInteger"/>
    </xs:attributeGroup>

    <!-- Connective types -->
    <xs:complexType name="binaryOp">
        <xs:sequence>
            <xs:element ref="criterion" minOccurs="2" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="connective" abstract="true"/>
    <xs:element name="and" substitutionGroup="connective" type="binaryOp"/>
    <xs:element name="or" type="binaryOp"/>
    <xs:element name="not">
        <xs:complexType>
            <xs:all>
                <xs:element ref="criterion"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <!-- Criterion types -->
    <xs:complexType name="stateCondition">
    </xs:complexType>
    <xs:complexType name="validationConstraint">
        <xs:complexContent>
            <xs:extension base="stateCondition">
                <xs:sequence>
                    <xs:element ref="criterion"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="criterion" type="criterion" abstract="true"/>
    <xs:element name="stateCondition" type="stateCondition" abstract="true"/>
    <xs:element name="validationConstraint" type="validationConstraint" abstract="true">
        <xs:complexType>
            <xs:all>
                <xs:element ref="criterion"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="criterion">
        <xs:choice>
            <xs:element ref="connective"/>
            <xs:element ref="stateCondition"/>
        </xs:choice>
    </xs:complexType>

    <!-- Lane criterion -->
    <xs:complexType name="lane">
        <xs:attribute name="id" type="xs:IDREF"/>
    </xs:complexType>
    <xs:element name="scLane" substitutionGroup="stateCondition"/>
    <xs:element name="vcLane" substitutionGroup="validationConstraint"/>
</xs:schema>

=== TrackerSB/DriveBuild/schemes/examples/environmentA.dbe.xml
<?xml version="1.0" encoding="UTF-8" ?>
<environment xmlns="http://drivebuild.com"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://drivebuild.com ../drivebuild.xsd">
    <author>Stefan Huber</author>

    <lanes>
        <lane>
            <laneSegment x="0" y="0" width="5"/>
            <laneSegment x="50" y="0" width="5"/>
            <laneSegment x="80" y="20" width="5"/>
            <laneSegment x="100" y="20" width="5"/>
        </lane>
    </lanes>

    <obstacles>
        <cone x="5" y="5" height="5" baseRadius="1"/>
    </obstacles>
</environment>

=== TrackerSB/DriveBuild/schemes/examples/criteriaA.dbc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<criteria xmlns="http://drivebuild.com"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://drivebuild.com ../drivebuild.xsd">
    <author>Stefan Huber</author>
    <version>1</version>
    <environment>environmentA.xml</environment>

    <participants>
        <participant id="ego">
            <initialState x="0" y="0" aiMode="manual" orientation="0" model="etk800"/>
            <ai address="localhost:5001"/>
        </participant>
    </participants>

    <failure>
        <scDamage participant="ego"/>
    </failure>
</criteria>

=== TrackerSB/DriveBuild/scratchPad/issueInvestigation/issue1/providedFiles/provided.dbe.xml
<?xml version='1.0' encoding='utf-8'?>
<environment xmlns="http://drivebuild.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://drivebuild.com drivebuild.xsd">
    <author>Stefan Huber</author>
    <timeOfDay>0</timeOfDay>
    <lanes>
        <lane markings="true">
            <laneSegment x="1.0" y="0.0" width="6" />
            <laneSegment x="7.928566676731771" y="2.6178515585789097" width="6" />
            <laneSegment x="11.976848269440552" y="7.49703112152404" width="6" />
            <laneSegment x="15.382297729992136" y="11.978168092945944" width="6" />
            <laneSegment x="19.070698211623846" y="15.197714000309226" width="6" />
            <laneSegment x="23.171205738178067" y="17.329079864496645" width="6" />
            <laneSegment x="27.5158261691661" y="18.847999420243458" width="6" />
            <laneSegment x="31.95515089768804" y="20.083860025291155" width="6" />
            <laneSegment x="36.40169682461469" y="21.194979571139566" width="6" />
            <laneSegment x="40.81239735394379" y="22.238586353598137" width="6" />
            <laneSegment x="45.17027663344325" y="23.24202546502637" width="6" />
            <laneSegment x="49.46759163999391" y="24.264927221460148" width="6" />
            <laneSegment x="53.69786831960522" y="25.40661219691853" width="6" />
            <laneSegment x="57.85574094513917" y="26.76544947901431" width="6" />
            <laneSegment x="61.93772522365379" y="28.392465544883198" width="6" />
            <laneSegment x="65.94297954012498" y="30.24543164898076" width="6" />
            <laneSegment x="69.87347478214923" y="32.16352030351826" width="6" />
            <laneSegment x="73.73218045507424" y="33.91095363206991" width="6" />
            <laneSegment x="77.52022552897323" y="35.256309750741494" width="6" />
            <laneSegment x="81.23399960405831" y="36.053904864964565" width="6" />
            <laneSegment x="84.86237790197565" y="36.32209543353761" width="6" />
            <laneSegment x="88.38607335564511" y="36.26867250125736" width="6" />
            <laneSegment x="91.78110425240054" y="36.21388888888889" width="6" />
            <laneSegment x="95.02348887957591" y="36.48296685751948" width="6" />
            <laneSegment x="98.09396904293257" y="37.297899940598526" width="6" />
            <laneSegment x="100.98252375371146" y="38.679473563951014" width="6" />
            <laneSegment x="103.69112938361617" y="40.43468267756163" width="6" />
            <laneSegment x="106.23452115582435" y="42.24148432277147" width="6" />
            <laneSegment x="108.64062478325778" y="43.74961402798059" width="6" />
            <laneSegment x="110.95096197109012" y="44.68125220436652" width="6" />
            <laneSegment x="113.21929218073778" y="44.912828338021285" width="6" />
            <laneSegment x="115.50235886562668" y="44.472386894134424" width="6" />
            <laneSegment x="117.84530987312856" y="43.479996387157776" width="6" />
            <laneSegment x="120.26666666666667" y="42.083333333333336" width="6" />
            <laneSegment x="122.7435617136471" y="40.39412965309092" width="6" />
            <laneSegment x="125.20395456273219" y="38.44713797772091" width="6" />
            <laneSegment x="127.53656305559522" y="36.21625778997542" width="6" />
            <laneSegment x="129.60777322801727" y="33.6531794689443" width="6" />
            <laneSegment x="131.27881757441403" y="30.72689352917277" width="6" />
            <laneSegment x="132.42286558295197" y="27.461583132051324" width="6" />
            <laneSegment x="132.9410786918634" y="23.955432359313907" width="6" />
            <laneSegment x="132.77713000416273" y="20.37114217706548" width="6" />
            <laneSegment x="131.93138105320676" y="16.92012633679185" width="6" />
            <laneSegment x="130.47502033112755" y="13.846605737207412" width="6" />
            <laneSegment x="128.55912208504802" y="11.409327846364878" width="6" />
            <laneSegment x="126.39292568813605" y="9.848895743170385" width="6" />
            <laneSegment x="124.195110616793" y="9.342471727999937" width="6" />
            <laneSegment x="122.14184002466344" y="9.956970147414477" width="6" />
            <laneSegment x="120.31523182097598" y="11.60277634620917" width="6" />
            <laneSegment x="118.67001012314692" y="14.009586226931043" width="6" />
            <laneSegment x="117.06113645688104" y="16.776441699887016" width="6" />
            <laneSegment x="115.30295796569618" y="19.46011382522721" width="6" />
            <laneSegment x="113.2301903134928" y="21.66571826619961" width="6" />
            <laneSegment x="110.75726821030432" y="23.134854256478267" width="6" />
            <laneSegment x="107.9096541882178" y="23.791201596595698" width="6" />
            <laneSegment x="104.8008916323731" y="23.70380658436213" width="6" />
            <laneSegment x="101.59348211775122" y="23.025827896375027" width="6" />
            <laneSegment x="98.45937979273644" y="21.932705995823266" width="6" />
            <laneSegment x="95.54231129564315" y="20.56492784740912" width="6" />
            <laneSegment x="92.93535140024444" y="19.00919398458576" width="6" />
            <laneSegment x="90.67588703785343" y="17.32335631777097" width="6" />
            <laneSegment x="88.74345103825414" y="15.568579717597316" width="6" />
            <laneSegment x="87.05765003369201" y="13.84140894939609" width="6" />
            <laneSegment x="85.48162854209744" y="12.295351162054258" width="6" />
            <laneSegment x="83.85031623612419" y="11.11552384798248" width="6" />
            <laneSegment x="82.01539241282181" y="10.461643679758966" width="6" />
            <laneSegment x="79.89166666666665" y="10.408333333333331" width="6" />
            <laneSegment x="77.50243679146564" y="10.886761751057417" width="6" />
            <laneSegment x="74.99823461357175" y="11.660991753040529" width="6" />
            <laneSegment x="72.60801811227498" y="12.392430917328465" width="6" />
            <laneSegment x="70.56375147150474" y="12.738989808406934" width="6" />
            <laneSegment x="69.02396398212568" y="12.455571935230086" width="6" />
            <laneSegment x="68.00170794758597" y="11.488735969765266" width="6" />
            <laneSegment x="67.34444346941058" y="10.002565945230193" width="6" />
            <laneSegment x="66.79090463288136" y="8.302557548099745" width="6" />
            <laneSegment x="66.04516214325483" y="6.736722787605576" width="6" />
            <laneSegment x="64.85086501452365" y="5.5964639574038095" width="6" />
            <laneSegment x="63.05723593964335" y="5.029355281207135" width="6" />
            <laneSegment x="60.63510006147119" y="5.024076327788507" width="6" />
            <laneSegment x="57.649075441974816" y="5.458647933683285" width="6" />
            <laneSegment x="54.22451774705999" y="6.156243038537177" width="6" />
            <laneSegment x="50.514586114543384" y="6.9407376131370455" width="6" />
            <laneSegment x="46.67290830089103" y="7.680630986796276" width="6" />
            <laneSegment x="42.845026662736394" y="8.293955366693263" width="6" />
            <laneSegment x="39.16955089795569" y="8.733022859735946" width="6" />
            <laneSegment x="35.779875854390355" y="8.967998763979498" width="6" />
            <laneSegment x="32.805727276003644" y="8.971020518759872" width="6" />
            <laneSegment x="30.371751581107134" y="8.709690535112292" width="6" />
            <laneSegment x="28.590386374028334" y="8.158705799420815" width="6" />
            <laneSegment x="27.553025826619116" y="7.316894736671207" width="6" />
            <laneSegment x="27.321148761365446" y="6.224376375082018" width="6" />
            <laneSegment x="27.918884079417435" y="4.9767923630511905" width="6" />
            <laneSegment x="29.337587883293324" y="3.7150772137372834" width="6" />
            <laneSegment x="31.554111447788443" y="2.587347187237908" width="6" />
            <laneSegment x="34.55132868216277" y="1.70618772702589" width="6" />
            <laneSegment x="38.33814685398005" y="1.1082208343092765" width="6" />
            <laneSegment x="42.93037211642412" y="0.8837752237788947" width="6" />
            <laneSegment x="48.156338173081494" y="2.068036312542734" width="6" />
            <laneSegment x="53.34433101965757" y="8.04584329402317" width="6" />
            <laneSegment x="57.0" y="26.0" width="6" />
        </lane>
    </lanes>
</environment>

=== TrackerSB/DriveBuild/scratchPad/issueInvestigation/issue2/providedFiles/tmpbbes0how.dbe.xml
<?xml version="1.0" encoding="UTF-8" ?>
<environment xmlns="http://drivebuild.com"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://drivebuild.com drivebuild.xsd">
    <author>Stefan Huber</author>
    <timeOfDay>0</timeOfDay>

    <lanes>
        
        <lane leftLanes="1" rightLanes="1">
            
            <laneSegment x="16.55349351675946" y="105.0" width="8.0"/>
            
            <laneSegment x="14.99620417958528" y="95.12200172502932" width="8.0"/>
            
            <laneSegment x="13.7400385070228" y="84.02631874772874" width="8.0"/>
            
            <laneSegment x="13.455705415270385" y="72.86337614182875" width="8.0"/>
            
            <laneSegment x="14.145368850841288" y="61.71813064092933" width="8.0"/>
            
            <laneSegment x="15.803780058560642" y="50.675404292975514" width="8.0"/>
            
            <laneSegment x="18.41831752776164" y="39.81923891325573" width="8.0"/>
            
            <laneSegment x="21.96908304960278" y="29.232256475441503" width="8.0"/>
            
            <laneSegment x="26.429053154452003" y="18.995030308479414" width="8.0"/>
            
            <laneSegment x="31.764284776807823" y="9.185471884906178" width="8.0"/>
            
            <laneSegment x="37.9341735825232" y="-0.1217621325015017" width="8.0"/>
            
            <laneSegment x="44.891762992305885" y="-8.85583807300958" width="8.0"/>
            
            <laneSegment x="52.58410154964011" y="-16.950284344931546" width="8.0"/>
            
            <laneSegment x="60.95264591334356" y="-24.343497324577783" width="8.0"/>
            
            <laneSegment x="69.93370640774316" y="-30.979210197029147" width="8.0"/>
            
            <laneSegment x="79.45893173956401" y="-36.80692118057331" width="8.0"/>
            
            <laneSegment x="89.4558291925426" y="-41.78227787575739" width="8.0"/>
            
            <laneSegment x="99.84831634077003" y="-45.86741481392849" width="8.0"/>
            
            <laneSegment x="110.557300081893" y="-49.031241636314036" width="8.0"/>
            
            <laneSegment x="121.50127858338038" y="-51.24967971042483" width="8.0"/>
            
            <laneSegment x="132.59696156068097" y="-52.5058453829873" width="8.0"/>
            
            <laneSegment x="143.75990416658092" y="-52.79017847473972" width="8.0"/>
            
            <laneSegment x="154.90514966748037" y="-52.10051503916881" width="8.0"/>
            
        </lane>
        
    </lanes>
</environment>

=== TrackerSB/DriveBuild/scratchPad/issueInvestigation/issue#3/providedFiles/testAcrit.dbc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<criteria xmlns="http://drivebuild.com"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://drivebuild.com drivebuild.xsd">
    <author>Bill Bosshard</author>
    <version>1</version>
    <name>Test</name>
    <environment>testAenv.dbe.xml</environment>
    <stepsPerSecond>10</stepsPerSecond>
    <aiFrequency>5</aiFrequency>

    <participants>
        <participant id="ego" model="ETK800">
            <initialState x="101.7994851745926" y="79.76461787394915" movementMode="_BEAMNG" orientation="-142.81"/>
            <movement>
                <waypoint x="105.0" y="79.68273471116593" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="97.03409425455126" y="73.6375427659398" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="89.78437121881038" y="67.61993536591707" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="83.08670461048452" y="60.993371782921976" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="76.99206771662467" y="53.80828416704959" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="71.54684440403553" y="46.11935537353122" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="66.79247611004158" y="37.98510279318769" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="62.76514644812622" y="29.467432999751416" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="59.495505828784744" y="20.63117060346007" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="57.008438191393324" y="11.543564896630542" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="55.32287162240501" y="2.2737780459381725" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="53.01302113897661" y="-10.429263193899525" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="49.6048173395884" y="-22.882648792147393" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="45.12419871308344" y="-34.99160096484294" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="39.60526547268092" y="-46.66396327436676" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="33.09002003276332" y="-57.81090199557826" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="25.62804734514117" y="-68.34758219410344" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="17.276137527629565" y="-78.19381337141007" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="8.097853656960801" y="-87.27465976292189" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-1.8369519846100246" y="-95.52101064443453" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-12.45266952735087" y="-102.87010630645688" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-23.66850695081599" y="-109.26601569349567" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-35.39910495990501" y="-114.66006207315986" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-47.555186620640036" y="-119.01119349548595" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-60.04423681154007" y="-122.28629522306507" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-72.77120631955765" y="-124.46044175418983" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-85.63923522198255" y="-125.51708652097282" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-98.55039004893894" y="-125.44818781871922" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-111.40640911622532" y="-124.2542700081554" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-124.10945035606304" y="-121.94441952472701" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-136.56283595431086" y="-118.53621572533883" movementMode="_BEAMNG" tolerance="1"/>
                <waypoint x="-148.67178812700644" y="-114.05559709883387" movementMode="_BEAMNG" tolerance="1"/>
            </movement>
        </participant>
    </participants>

    <success>
        <scPosition participant="ego" x="-148.67178812700644" y="-114.05559709883387" tolerance="4.0"/>
    </success>

    <failure>
        <or>
            <scDamage participant="ego"/>
            <scLane participant="ego" onLane="offroad"/>
        </or>
    </failure>
</criteria>

=== TrackerSB/DriveBuild/examples/mooseTest/scenario/mooseTest.dbe.xml
<?xml version="1.0" encoding="UTF-8" ?>
<environment xmlns="http://drivebuild.com"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://drivebuild.com drivebuild.xsd">
    <author>Stefan Huber</author>
    <timeOfDay>0</timeOfDay>
    <lanes>
        <lane>
            <!-- Ensure straight start segment -->
            <laneSegment x="-45" y="4" width="8" />
            <laneSegment x="-35" y="4" width="8" />
            <laneSegment x="-25" y="4" width="8" />
            <laneSegment x="-15" y="4" width="8" />
            <!-- NOTE: w1=8, w2=8, w3=3, intensity=1 -->
            <laneSegment x="0" y="4" width="8" />
            <laneSegment x="12" y="4" width="8" />
            <laneSegment x="25.5" y="13" width="8" />
            <laneSegment x="36.5" y="13" width="8" />
            <laneSegment x="49" y="4" width="8" />
            <laneSegment x="61" y="4" width="8" />
        </lane>
    </lanes>
</environment>
